import pandas as pd
import os
import subprocess
import sys
import argparse
from loguru import logger
from sqlalchemy import create_engine
import concurrent.futures
import zipfile
import shutil
from datetime import datetime

# -------------------------------------------------------------------
# A quick-lookup set of FULL normalized hospital addresses.
# Add / update as needed.  All entries must be lower-case and trimmed.
HOSPITAL_ADDRESSES = {
    "1000 peachtree park dr ne atlanta ga 30309",
    "240 nw 25th st miami fl 33127",
    "1400 briarcliff rd ne atlanta ga 30306",
    # …extend the list …
}
# -------------------------------------------------------------------

# logger.add(sys.stderr, format="{time} {level} {message}", filter="my_module", level="INFO")
#get the log file
def configure_logging(output_folder):
    # Create log subfolder inside the output folder
    log_folder = os.path.join(output_folder, "log")
    os.makedirs(log_folder, exist_ok=True)

    # Create log filename based on current timestamp
    log_filename = f"address_to_fips_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    log_file_path = os.path.join(log_folder, log_filename)

    # Ensure the output folder exists
    os.makedirs(output_folder, exist_ok=True)
    logger.remove()  # Remove any previous handlers (reset the logger)

    # Configure logger to output to both the console and the log file
    logger.add(sys.stderr, format="{time} {level} {message}", level="DEBUG")  # Logs everything to terminal
    logger.add(log_file_path, format="{time} {level} {message}", level="DEBUG")  # Logs everything to file
    logger.info(f"Log file configured: {log_file_path}")

    return log_file_path  # Return the log file path for reference if needed

#Generate latitude and longitude from address infomation
def generate_coordinates_degauss(df, columns, threshold, output_folder):
    """
    Preprocess address data, execute a Docker-based geocoding tool, and retrieve geolocation data using Degauss.
    
    Parameters:
    df (pandas.DataFrame): DataFrame containing address data
    columns (list of str): List of column names representing address information
    threshold (float): Threshold for the geocoder's score (accuracy)
    save_intermediate (bool): Whether to save the intermediate preprocessed CSV before geocoding (default is False)
    
    Returns:
    str: Name of the geocoded CSV file generated by the Docker container
    """
    logger.info("Generating coordinates...")

    orig_df = df.copy(deep=True)
    orig_df["_rid"] = orig_df.index
    df["_rid"]      = orig_df["_rid"]

    if "zip" in orig_df.columns:
        orig_df["zip"] = (
            orig_df["zip"]
            .fillna("")                # keep dtype object
            .astype(str)
            .str.replace(r"\.0$", "", regex=True)  # drop trailing '.0'
            .str.strip()
        )
    
    # Convert columns to string type
    for col in columns:
        df[col] = df[col].fillna("").astype(str)
    for col in columns:
         # If this is the Zip column, ensure no '.0' remains
        if col.lower() == 'zip':
            df[col] = df[col].apply(lambda x: x.split('.')[0] if '.' in x else x)
    
    # Handle single column or concatenate multiple columns
    if len(columns) == 1:
        df['address'] = df[columns[0]].str.title().replace(r'[^a-zA-Z0-9 ]', ' ', regex=True)
    else:
        df['address'] = df.apply(lambda row: ' '.join(row[columns]).lower(), axis=1)
        df['address'] = df['address'].str.title()
        df['address'] = df['address'].replace(r'[^a-zA-Z0-9 ]', ' ', regex=True)

    # Reorder columns to ensure 'address' is the first column
    cols = ['address'] + [col for col in df.columns if col != 'address']
    df = df[cols]
    
    # Drop original address columns if they are no longer needed
    if len(columns) > 1:
        df.drop(columns=columns, inplace=True)
    
    # Save the preprocessed DataFrame to CSV
    preprocessed_file_path = os.path.join(output_folder, 'preprocessed_1.csv')
    df.to_csv(preprocessed_file_path, index=False)

    # Convert the folder and file paths to absolute paths for Docker
    abs_output_folder = os.path.abspath(output_folder)  # Convert to absolute path
    abs_preprocessed_file = os.path.abspath(preprocessed_file_path)  # Convert to absolute path

      # Quote the paths to handle spaces
    quoted_output_folder = f'"{abs_output_folder}"'
    quoted_preprocessed_file = f'"{abs_preprocessed_file}"'
    
    # Define the Docker command
    docker_command = [
        'docker', 'run', '--rm',
        '-v', f'{quoted_output_folder}:/tmp',
        'ghcr.io/degauss-org/geocoder:3.3.0',
       f'/tmp/{os.path.basename(abs_preprocessed_file)}',
        str(threshold)
    ]
    
    try:
        result = subprocess.run(' '.join(docker_command), shell=True, check=True, capture_output=True, text=True)
        logger.info("Docker command executed successfully.")
        logger.info(result.stdout)
    except subprocess.CalledProcessError as e:
        logger.error(f"Error executing Docker command: {e}")
        logger.error(e.stderr)

    # Define the output file name
    output_file_name = os.path.join(output_folder, f"preprocessed_1_geocoder_3.3.0_score_threshold_{threshold}.csv")

  

    try:
        # read the geocoder output
        geocoded_df = pd.read_csv(output_file_name)

        # bring the original address pieces back in (needed for the reason logic)
        merge_cols = [c for c in ("street", "city", "state", "zip") if c in orig_df.columns]
        geocoded_df = (
            geocoded_df
            .merge(orig_df[merge_cols + ["_rid"]], on="_rid", how="left")
            .sort_values("_rid")
            .reset_index(drop=True)
        )

        # ── helpers ────────────────────────────────────────────────
        MISSING_SENTINELS = {"nan", "na", "n/a", "none", "null", ""}

        def _blank(x: object) -> bool:
            return pd.isna(x) or str(x).strip().lower() in MISSING_SENTINELS

        def _has_coords(row) -> bool:
            """Return True **only** if lat/lon are real numbers inside
            normal geographic limits (and not NaN)."""
            try:
                lat = float(row.get("lat", ""))
                lon = float(row.get("lon", ""))
            except (ValueError, TypeError):
                return False
            if pd.isna(lat) or pd.isna(lon):
                return False
            return -90.0 <= lat <= 90.0 and -180.0 <= lon <= 180.0

        def _zip_clean(z):
            z = str(z).strip().lower()
            return z[:-2] if z.endswith(".0") else z

        def _reason(row):
            # ----- Successful geocode – hospital address test -----
            if row["geocode_result"] == "geocoded":
                if {"street", "city", "state", "zip"}.issubset(row.index):
                    full_addr = " ".join(
                        [
                            str(row.get("street", "")).strip().lower(),
                            str(row.get("city", "")).strip().lower(),
                            str(row.get("state", "")).strip().lower(),
                            _zip_clean(row.get("zip", "")),
                        ]
                    ).strip()
                else:  # single-column case
                    full_addr = (
                        str(row.get("address", ""))
                        .lower()
                        .strip()
                    )
                return "Hospital address given" if full_addr in HOSPITAL_ADDRESSES else ""

            # ----- Imprecise geocode – why? -----
            if all(_blank(row.get(c, "")) for c in ("street", "city", "state", "zip")):
                return "Blank/Incomplete address"
            if _blank(row.get("zip", "")):
                return "Zip missing"
            if _blank(row.get("street", "")):
                return "Street missing"
            return ""

        # rebuild geocode_result & reason
        geocoded_df.drop(columns=["geocode_result"], errors="ignore", inplace=True)
        geocoded_df["geocode_result"] = geocoded_df.apply(
            lambda r: "geocoded" if _has_coords(r) else "imprecise_geocode",
            axis=1,
        )
        geocoded_df["reason"] = geocoded_df.apply(_reason, axis=1)

        # tidy-up: remove auxiliary cols (_rid) but KEEP 'address'
        geocoded_df.drop(columns=[c for c in geocoded_df.columns if c.startswith("_")],
                         inplace=True, errors="ignore")
        geocoded_df.drop(columns=merge_cols, inplace=True, errors="ignore")

        # normalise year (no trailing “.0”)
        if "year" in geocoded_df.columns:
            geocoded_df["year"] = pd.to_numeric(
                geocoded_df["year"], errors="coerce"
            ).astype("Int64")

        # save
        geocoded_df.to_csv(output_file_name, index=False)
        logger.info("geocode_result / reason fixed, _rid removed.")

    except Exception as e:
        logger.warning(f"Could not post-process geocoder output: {e}")

    return os.path.abspath(output_file_name)


#Generate the FIPS code from latitude and longitude
def generate_fips_degauss(df, year, output_folder):
    logger.info("Generating FIPS...")
    """
    Generates FIPS codes from latitude and longitude using a Docker-based geocoding service.

    This function saves the provided DataFrame to a CSV file, runs a Docker container to process this file
    and generate FIPS codes, and then updates the DataFrame with the FIPS codes before saving the final output.

    Parameters:
    df (pd.DataFrame): The input DataFrame containing latitude and longitude data.
    year (int): The year to be used for different FIPS code version.

    Returns:
    str or None: The path to the output file if successful, None otherwise.
    """

    # Convert the folder and file paths to absolute paths
    abs_output_folder = os.path.abspath(output_folder)  # Convert to absolute path
    
    # Normalize the paths to Unix-style for Docker (replace backslashes with forward slashes)
    abs_output_folder = abs_output_folder.replace("\\", "/")
    
    preprocessed_file_path = os.path.join(output_folder, 'preprocessed_2.csv')
    # Columns that may exist and need to be dropped
    columns_to_drop = {'matched_street', 'matched_zip', 'matched_city', 'matched_state', 'score', 'precision', 'address'}
    # Drop only the columns that exist in the DataFrame
    columns_in_df = set(df.columns)  # Get the columns that exist in the DataFrame
    columns_to_drop = columns_to_drop.intersection(columns_in_df)  # Find intersection of existing columns and columns to drop
    
    if columns_to_drop:  # Only drop if there are columns to drop
        df.drop(columns=columns_to_drop, inplace=True)
        
    df.to_csv(preprocessed_file_path, index=False)

    # Also normalize the preprocessed file path
    abs_preprocessed_file = os.path.abspath(preprocessed_file_path).replace("\\", "/")
    
    output_file = os.path.join(output_folder, f"preprocessed_2_census_block_group_0.6.0_{year}.csv")    
#     output_file = f"{df.replace('.csv', '')}_census_block_group_0.6.0_{year}.csv"
    docker_command2 = ["docker", "run", "--rm", "-v", f'{abs_output_folder}:/tmp', "ghcr.io/degauss-org/census_block_group:0.6.0", f'/tmp/{os.path.basename(abs_preprocessed_file)}', str(year)]
    try:
        result = subprocess.run(docker_command2, check=True, capture_output=True, text=True)
        logger.info("Docker command executed successfully.")
        logger.info(result.stdout)
    except subprocess.CalledProcessError as e:
        logger.error(f"Error executing Docker command 2: {e}")
        logger.error(e.stderr)
        return None

    # Define the output file name
    output_file = os.path.join(output_folder, f"preprocessed_2_census_block_group_0.6.0_{year}.csv")
    output_file = os.path.abspath(output_file).replace("\\", "/")

    if os.path.exists(output_file):
        logger.info(f"Output file generated: {output_file}")
        df = pd.read_csv(output_file)
        df['FIPS'] = df[f'census_tract_id_{year}']
        df.drop(columns=[f'census_block_group_id_{year}', f'census_tract_id_{year}'], inplace=True)
        df.to_csv(output_file, index=False)
        return output_file
    else:
        logger.error(f"Expected output file not found: {output_file}")
        return None

# Function to process each individual CSV file
def process_csv_file(file, input_folder, args, final_coordinate_files):
    file_path = os.path.join(input_folder, file)
        
    # Create a new folder for each CSV file
    output_folder = os.path.join(input_folder, file.replace('.csv', ''))
    os.makedirs(output_folder, exist_ok=True)
    
    logger.info(f"Processing file: {file_path}")

    # Step 1: Check if latitude and longitude are provided (skip geocode if present)
    if args.option == 3:
        logger.info("Using provided latitude and longitude columns, skipping geocoding.")
        df = pd.read_csv(file_path)
        df.rename(columns={'latitude': 'lat', 'longitude': 'lon'}, inplace=True)
        df['year_for_fips'] = df['year'].apply(lambda x: 2010 if x < 2020 else 2020)

    # Step 2: If latitude and longitude are not provided, check for address columns
    elif args.option in [1, 2]:
        logger.info("Latitude and longitude not provided. Using address columns for geocoding.")
        threshold = 0.7

        # Set the columns based on the option
        if args.option == 1:
            columns = ['street', 'city', 'state', 'zip']
        elif args.option == 2:
            columns = ['address']

        df = pd.read_csv(file_path)
        geocoded_file = generate_coordinates_degauss(df, columns, threshold, output_folder)
        logger.info(f"Geocoded file created: {geocoded_file}")

        # Load geocoded file after processing
        df = pd.read_csv(geocoded_file)
        df['year_for_fips'] = df['year'].apply(lambda x: 2010 if x < 2020 else 2020)

         # Rename columns and drop unnecessary ones
        latlon = pd.read_csv(geocoded_file)
        columns_to_drop = ['matched_street', 'matched_zip', 'matched_city', 'matched_state', 'score', 'precision', 'address']
        latlon.drop(columns=[col for col in columns_to_drop if col in latlon.columns], inplace=True)
        latlon.rename(columns={'lat': 'latitude', 'lon': 'longitude'}, inplace=True)
        
        # Save the file with coordinates
        base_filename = os.path.splitext(file)[0]
        output_file = os.path.join(output_folder, f"{base_filename}_with_coordinates.csv")
        latlon.to_csv(output_file, index=False)
        # Add coordinate file to the final_coordinate_files list
        final_coordinate_files.append(output_file)

    else:
        logger.error("You must provide either address columns (for geocoding) or latitude and longitude.")
        return None

    # Step 3: Process FIPS generation for 2010 and 2020
    has_2010 = (df['year_for_fips'] == 2010).any()
    has_2020 = (df['year_for_fips'] == 2020).any()

    # Generate FIPS codes based on available years
    if has_2010 and has_2020:
        for Year in [2010, 2020]:
            year_df = df[df['year_for_fips'] == Year]
            generate_fips_degauss(year_df, Year, output_folder)

    elif has_2010:
        year_df_2010 = df[df['year_for_fips'] == 2010]
        generate_fips_degauss(year_df_2010, 2010, output_folder)

    elif has_2020:
        year_df_2020 = df[df['year_for_fips'] == 2020]
        generate_fips_degauss(year_df_2020, 2020, output_folder)

    else:
        logger.warning("No data available for 2010 or 2020.")

    # Final output CSV file
    base_filename = os.path.splitext(file)[0]
    encounter_with_fips_file = os.path.join(output_folder, f"{base_filename}_with_fips.csv")

    fips_file_2010 = os.path.join(output_folder, "preprocessed_2_census_block_group_0.6.0_2010.csv")
    fips_file_2020 = os.path.join(output_folder, "preprocessed_2_census_block_group_0.6.0_2020.csv")

    if os.path.exists(fips_file_2010) and os.path.exists(fips_file_2020):
        fips_df_2010 = pd.read_csv(fips_file_2010)
        fips_df_2020 = pd.read_csv(fips_file_2020)
        all_fips_df = pd.concat([fips_df_2010, fips_df_2020], ignore_index=True)
        all_fips_df.drop(columns=['year_for_fips'], inplace=True)
        all_fips_df.rename(columns={'lat': 'latitude', 'lon': 'longitude'}, inplace=True)
        all_fips_df.to_csv(encounter_with_fips_file, index=False)
        logger.info(f"Encounter with FIPS file generated: {encounter_with_fips_file}")

    elif os.path.exists(fips_file_2010):
        fips_df_2010 = pd.read_csv(fips_file_2010)
        fips_df_2010.drop(columns=['year_for_fips'], inplace=True)
        fips_df_2010.rename(columns={'lat': 'latitude', 'lon': 'longitude'}, inplace=True)
        fips_df_2010.to_csv(encounter_with_fips_file, index=False)
        logger.info(f"FIPS file generated for 2010 with {len(fips_df_2010)} rows: {encounter_with_fips_file}")

    elif os.path.exists(fips_file_2020):
        fips_df_2020 = pd.read_csv(fips_file_2020)
        fips_df_2020.drop(columns=['year_for_fips'], inplace=True)
        fips_df_2020.rename(columns={'lat': 'latitude', 'lon': 'longitude'}, inplace=True)
        fips_df_2020.to_csv(encounter_with_fips_file, index=False)
        logger.info(f"FIPS file generated for 2020 with {len(fips_df_2020)} rows: {encounter_with_fips_file}")

    else:
        logger.error("Error: Neither FIPS file exists.")

    return encounter_with_fips_file

        
def main():
    parser = argparse.ArgumentParser(description='FIPS Geocoding')
    parser.add_argument('-i', '--input', type=str, required=True, help='Input folder path containing CSV files')
    parser.add_argument('--debug', dest='debug', action='store_true', help='Enable debug logging')
    parser.add_argument('-o', '--option', type=int, choices=[1, 2, 3], required=True, 
                        help='Option for input type: 1 = street, city, state, zip; 2 = address; 3 = latitude, longitude')
    
    args = parser.parse_args()
    input_folder = args.input
    parent_folder = os.path.dirname(input_folder)
    output_folder = os.path.join(parent_folder, "output")

    #Configure logging to write to the output folder
    configure_logging(output_folder)

    # Generate timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

     # Handle each option case
    if args.option == 1:
        columns = ['street', 'city', 'state', 'zip']
        logger.info(f"Option 1 selected: street={columns[0]}, city={columns[1]}, state={columns[2]}, zip={columns[3]}")

    elif args.option == 2:
        columns = ['address']
        logger.info(f"Option 2 selected: address={columns[0]}")

    elif args.option == 3:
        latitude = 'latitude'
        longitude = 'longitude'
        logger.info(f"Option 3 selected: latitude={latitude}, longitude={longitude}")

    
    csv_files = [f for f in os.listdir(input_folder) if f.endswith('.csv')]

    final_fips_files = []  # Collect all final fips files for zipping
    final_coordinate_files = []  # Collect all final coordinate files for zipping

   # Step 1: Use ThreadPoolExecutor to process up to 10 files concurrently
    with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
        futures = {executor.submit(process_csv_file, file, input_folder, args, final_coordinate_files): file for file in csv_files}

        for future in concurrent.futures.as_completed(futures):
            file = futures[future]
            try:
                result = future.result()
                if result:
                    final_fips_files.append(result)
            except Exception as e:
                logger.error(f"Error processing file {file}: {e}")

    # Step 2: Package all final output files into a zip
    #Create the 'output' folder parallel to the input folder
    
    os.makedirs(output_folder, exist_ok=True)

    zip_filename = os.path.join(output_folder, f"geocoded_fips_codes_{timestamp}.zip")
    
    with zipfile.ZipFile(zip_filename, 'w') as zipf:
        for final_file in final_fips_files:
            if os.path.exists(final_file):  # Only include files that exist
                zipf.write(final_file, os.path.basename(final_file))  # Add the file to the zip archive
            else:
                logger.error(f"Skipping missing file: {final_file}")

    logger.info(f"All output files zipped into: {zip_filename}")

    # Step 3: Package all final coordinate files into a zip
    if final_coordinate_files:  # Check if the list is not empty
        zip_coordinates_filename = os.path.join(output_folder, f"coordinates_from_address_{timestamp}.zip")
    
        with zipfile.ZipFile(zip_coordinates_filename, 'w') as zipf:
            for coord_file in final_coordinate_files:
                if os.path.exists(coord_file):  # Only include files that exist
                    zipf.write(coord_file, os.path.basename(coord_file))  # Add the file to the zip archive
                else:
                    logger.error(f"Skipping missing file: {coord_file}")

        logger.info(f"All coordinate output files zipped into: {zip_coordinates_filename}")
    else:
        logger.warning("No coordinate files to zip. Skipping the creation of coordinates_from_address.zip.")
        
    # Step 4: Remove all the subdirectories, but keep the zip files
    logger.info("Cleaning up subdirectories...")
    for root, dirs, files in os.walk(input_folder, topdown=False):
        for dir_name in dirs:
            dir_path = os.path.join(root, dir_name)
            if os.path.isdir(dir_path):
                shutil.rmtree(dir_path)
                logger.info(f"Deleted directory: {dir_path}")

    logger.info("Cleanup completed. Only zip files and log file remain in the input folder.")



if __name__ == "__main__":
    main()
                
    
    
